# docker compose -f compose.{ENVIRONMENT}.yml  up

services:
  postgres:
    image: postgres
    container_name: nest_jobs_${NODE_ENV}_postgres
    restart: unless-stopped
    environment:
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=${DATABASE_NAME}
    ports:
      - ${DATABASE_PORT}:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data/
volumes:
  postgres_data:
    driver: local
